// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzppkiwucwxdopggylmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6cHBraXd1Y3d4ZG9wZ2d5bG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NTM2ODksImV4cCI6MjA1MzAyOTY4OX0.psSYEMD0jKzAlmSs06PSa0anp5Jj9v2GIUJm9qnzY2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);